global using Confluent.Kafka;
global using Dapper;
global using FastEndpoints;
global using FastEndpoints.Swagger;
global using IdGen;
global using Npgsql;
global using MassTransit;
global using Microsoft.AspNetCore.Http.HttpResults;
global using Microsoft.Extensions.Options;
global using QuizSession.API;
global using QuizSession.API.Abstraction;
global using QuizSession.API.DbContext;
global using QuizSession.API.DbContext.Entities;
global using QuizSession.API.DbContext.Migration;
global using QuizSession.API.Events;
global using QuizSession.API.Repositories;
global using System.Data;
global using System.Text.Json;

global using Mapper = Riok.Mapperly.Abstractions.MapperAttribute;